#################################################################################################################
# +-----------------------------------------------------------------------------------------------------------+ #
#  _______        |                              .           .             .                                  | #
# '   /      ___  \ ___   |     ___  _/_           /|    ____  `   ___  , __     ___/   ___   |     ___       | #
#     |     /   ` |/   \  |   .'   `  |           /  \      /  | .'   ` |'  `.  /   |  /   `  |   .'   `      | #
#     |    |    | |    `  |   |----'  |          /---'\   ,/   | |----' |    | ,'   | |    |  |   |----'      | #
#     /    `.__/| `___,' /\___`.___,  \__/     ,'      \ /__.' / `.___, /    | `___,' `.__/| /\___`.___,      | #
#                                                        `                          `                         | #
# |                                                                                                           | #
# |                                                                                                           | #
# |                                                                                                           | #
# |                                                                                                           | #
# |  TELEGRAM:    https://t.me/PhRedssWorks                                                                   | #
# |  BUG REPORTS: @SignorReds                                                                                 | #
# |                                                                                                           | #
# |                                                                                                           | #
# |                                                                                                           | #
# |                                                                                                           | #
# |                                                                                                           | #
# |                                                                                                           | #
# +-----------------------------------------------------------------------------------------------------------+ #
#################################################################################################################


LICENSE-KEY: 'YOUR-LICENSE-KEY'

pex-format: "{agency}-{role}"