name: TabletAziendale
version: ${spigot.version}
main: me.phredss.tabletaziendale.TabletAziendale
api-version: 1.16
commands:
  azienda:
    description: Comando Azienda
    aliases:
      - az
    usage: /<command>
  prova:
    description: blabla
    usage: </command>