name: AgencyHelper
version: 0.1
main: me.phredss.tabletaziendale.TabletAziendale
api-version: 1.16
authors: [_PhReds]
depend: [LuckPerms]
commands:
  agency:
    description: Agency Helper
    aliases:
      - ag
      - azienda
      - az